# -*- coding: utf-8 -*-
"""Draft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zvtlohxz9vc1bSU--8ZqkCvDagjZb0JO
"""

import pandas as pd
import numpy as np
import nltk
import re
import string
from nltk.stem import PorterStemmer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from nltk.corpus import stopwords
import gradio as gr  # Import Gradio

# Stemming and stopwords
stemmer = nltk.SnowballStemmer("english")
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Load dataset
data = pd.read_csv("/content/Twitter_Hate_Speech.csv")
data["labels"] = data["class"].map({0: "Hate Speech", 1: "Offensive Language", 2: "Normal"})

# Clean text
def clean(text):
    text = str(text).lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    text = " ".join([word for word in text.split() if word not in stop_words])
    return text

data["tweet"] = data["tweet"].apply(clean)

# Prepare data for model training
x = np.array(data["tweet"])
y = np.array(data["labels"])
cv = CountVectorizer()
X = cv.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Train the Decision Tree Classifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# Define a prediction function for Gradio
def classify_tweet(tweet):
    cleaned_tweet = clean(tweet)
    vectorized_tweet = cv.transform([cleaned_tweet])
    prediction = clf.predict(vectorized_tweet)[0]
    return f"Predicted Label: {prediction}"

# Build Gradio Interface
interface = gr.Interface(
    fn=classify_tweet,  # Function to call for predictions
    inputs="text",      # Input type (a text box)
    outputs="text",     # Output type (text display)
    title="Twit Safe: Hate Speech Classifier",
    description="Enter a tweet to classify it as Hate Speech, Offensive Language, or Normal."
)

# Launch the interface
interface.launch()

from google.colab import drive
drive.mount('/content/drive')
